name: buildx

on:
  push:
    branches:
      - 'main'
      - 'development'
      - 'staging'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2

          #- name: set vars per branch
          #  env:
          #    REACT_APP_ALCHEMY_API_KEY: "${{ secrets.REACT_APP_ALCHEMY_API_KEY }}"
          #    REACT_APP_WEB3_MODAL_PROJECT_ID: "${{ secrets.REACT_APP_WEB3_MODAL_PROJECT_ID }}"
          #    REACT_APP_BEE_URL: "${{ vars.REACT_APP_BEE_URL }}"
          #    REACT_APP_BEE_DEBUG_URL: "${{ vars.REACT_APP_BEE_DEBUG_URL }}"
          #    REACT_APP_FAIROS_URL: "${{ vars.REACT_APP_FAIROS_URL }}"
          #    REACT_APP_BLOCKCHAIN_INFO: "${{ vars.REACT_APP_BLOCKCHAIN_INFO }}"
          #    REACT_APP_ENVIRONMENT: "${{ vars.REACT_APP_ENVIRONMENT }}"
          #    REACT_APP_INVITE_URL: "${{ vars.REACT_APP_INVITE_URL: }}"
          #  id: vars
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: |
            linux/amd64
          build-args: |
            "REACT_APP_ALCHEMY_API_KEY=${{ secrets.REACT_APP_ALCHEMY_API_KEY }}"
            "REACT_APP_WEB3_MODAL_PROJECT_ID=${{ secrets.REACT_APP_WEB3_MODAL_PROJECT_ID }}"
            "REACT_APP_BEE_URL=${{ vars.REACT_APP_BEE_URL }}"
            "REACT_APP_BEE_DEBUG_URL=${{ vars.REACT_APP_BEE_DEBUG_URL }}"
            "REACT_APP_FAIROS_URL=${{ vars.REACT_APP_FAIROS_URL }}"
            "REACT_APP_BLOCKCHAIN_INFO=${{ vars.REACT_APP_BLOCKCHAIN_INFO }}"
            "REACT_APP_ENVIRONMENT=${{ vars.REACT_APP_ENVIRONMENT }}"
            "REACT_APP_INVITE_URL=${{ vars.REACT_APP_INVITE_URL }}"
          tags: fairdatasociety/${{ github.repository }}:latest
